# -*- coding: utf-8 -*-
"""运行时组件协议，便于真机与模拟实现互换。"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol

from .types import Detection, DirectPlaceTarget, RobotReply


class CameraLike(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_frame(self) -> Any: ...
    def flush(self) -> None: ...
    def measure_depth_mm(self, bundle: Any, bbox: tuple[int, int, int, int]) -> float: ...


class DetectorLike(Protocol):
    def detect(self, image: Any) -> list[Detection]: ...
    def annotate(self, image: Any, detections: list[Detection]) -> Any: ...


class CalibrationLike(Protocol):
    def locate(self, pixel: tuple[int, int], depth_mm: float, intrinsics: Any) -> tuple[
        tuple[float, float, float], tuple[float, float, float]
    ]: ...
    def image_axis_to_robot_rz_deg(
        self,
        center_pixel: tuple[int | float, int | float],
        axis_pixel: tuple[int | float, int | float],
        depth_mm: float,
        intrinsics: Any,
    ) -> float: ...
    def object_height_mm(self, depth_mm: float) -> float: ...


class DVSLike(Protocol):
    def is_connected(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def trigger(self) -> bool: ...
    def wait_for_result(
        self, timeout: float | None = None, *, after_sequence: int | None = None
    ) -> Mapping[str, Any] | None: ...


class RobotLike(Protocol):
    @property
    def is_connected(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def wait_connected(self, timeout_s: float) -> bool: ...
    def go_photo(self) -> RobotReply: ...
    def is_at_photo(self) -> RobotReply: ...
    def pick_and_place_direct(self, target: DirectPlaceTarget) -> RobotReply: ...
    def request_stop(self) -> None: ...
